# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "59eea0a0ef538723f69ea07f5caf8b1c"
name = "BehavioralPro Public"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
