create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  shop_domain text not null,
  route text not null,
  submitted_at timestamptz not null default timezone('utc', now()),
  type text not null check (type in ('Bug Report', 'Feature Recommendation')),
  description text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists feedback_shop_domain_created_at_idx
  on public.feedback (shop_domain, created_at desc);

create index if not exists feedback_type_created_at_idx
  on public.feedback (type, created_at desc);
