create extension if not exists pgcrypto;

create table if not exists public.storefront_intervention_variants (
  id uuid primary key default gen_random_uuid(),
  shop_domain text not null,
  store_id text,
  cohort_key text not null default 'mdp_default',
  variant_key text not null,
  variant_label text not null,
  message_id text,
  intervention_type text not null default 'dynamic_message',
  payload jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  priority smallint not null default 0,
  prior_alpha numeric(18,6) not null default 1.000000,
  prior_beta numeric(18,6) not null default 1.000000,
  alpha numeric(18,6) not null default 1.000000,
  beta numeric(18,6) not null default 1.000000,
  successes_count bigint not null default 0,
  failures_count bigint not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (shop_domain, cohort_key, variant_key)
);

create index if not exists storefront_intervention_variants_shop_domain_idx
  on public.storefront_intervention_variants (shop_domain, cohort_key, is_active);

create table if not exists public.storefront_trajectory_bandit_state (
  id bigint generated by default as identity primary key,
  shop_domain text not null,
  store_id text,
  cohort_key text not null default 'mdp_default',
  trajectory_key text not null,
  variant_id uuid not null references public.storefront_intervention_variants (id) on delete cascade,
  alpha numeric(18,6) not null default 1.000000,
  beta numeric(18,6) not null default 1.000000,
  successes_count bigint not null default 0,
  failures_count bigint not null default 0,
  first_seen_at timestamptz not null default timezone('utc', now()),
  last_seen_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (shop_domain, cohort_key, trajectory_key, variant_id)
);

create index if not exists storefront_trajectory_bandit_state_lookup_idx
  on public.storefront_trajectory_bandit_state (shop_domain, cohort_key, trajectory_key);

create table if not exists public.storefront_intervention_sessions (
  id bigint generated by default as identity primary key,
  shop_domain text not null,
  store_id text,
  cohort_key text not null default 'mdp_default',
  session_id text not null,
  trajectory_key text not null,
  variant_id uuid not null references public.storefront_intervention_variants (id) on delete cascade,
  reward_status text not null default 'pending'
    check (reward_status in ('pending', 'success', 'failure')),
  assigned_at timestamptz not null default timezone('utc', now()),
  rewarded_at timestamptz,
  converted_at timestamptz,
  checkout_order_id text,
  metadata jsonb not null default '{}'::jsonb,
  unique (shop_domain, session_id)
);

create index if not exists storefront_intervention_sessions_pending_idx
  on public.storefront_intervention_sessions (reward_status, assigned_at);

create index if not exists storefront_intervention_sessions_trajectory_idx
  on public.storefront_intervention_sessions (shop_domain, trajectory_key, assigned_at desc);

create or replace function public.touch_storefront_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists storefront_intervention_variants_touch_updated_at
  on public.storefront_intervention_variants;
create trigger storefront_intervention_variants_touch_updated_at
before update on public.storefront_intervention_variants
for each row execute function public.touch_storefront_updated_at();

drop trigger if exists storefront_trajectory_bandit_state_touch_updated_at
  on public.storefront_trajectory_bandit_state;
create trigger storefront_trajectory_bandit_state_touch_updated_at
before update on public.storefront_trajectory_bandit_state
for each row execute function public.touch_storefront_updated_at();

create or replace function public.apply_storefront_bandit_decay(
  p_gamma numeric default 0.90
)
returns table (
  variants_updated bigint,
  trajectories_updated bigint,
  gamma numeric
)
language plpgsql
security definer
as $$
declare
  v_variants_updated bigint := 0;
  v_trajectories_updated bigint := 0;
  v_gamma numeric := greatest(0.000001, least(coalesce(p_gamma, 0.90), 0.999999));
begin
  update public.storefront_intervention_variants
  set
    alpha = round(prior_alpha + ((alpha - prior_alpha) * v_gamma), 6),
    beta = round(prior_beta + ((beta - prior_beta) * v_gamma), 6),
    updated_at = timezone('utc', now())
  where is_active = true;

  get diagnostics v_variants_updated = row_count;

  update public.storefront_trajectory_bandit_state state
  set
    alpha = round(
      variant.prior_alpha + ((state.alpha - variant.prior_alpha) * v_gamma),
      6
    ),
    beta = round(
      variant.prior_beta + ((state.beta - variant.prior_beta) * v_gamma),
      6
    ),
    updated_at = timezone('utc', now())
  from public.storefront_intervention_variants variant
  where variant.id = state.variant_id
    and variant.is_active = true;

  get diagnostics v_trajectories_updated = row_count;

  return query
  select v_variants_updated, v_trajectories_updated, v_gamma;
end;
$$;

create or replace function public.reconcile_storefront_bandit_failures(
  p_cutoff interval default interval '4 hours'
)
returns table (
  processed_sessions bigint
)
language plpgsql
security definer
as $$
declare
  session_row record;
  processed bigint := 0;
  variant_prior_alpha numeric := 1.000000;
  variant_prior_beta numeric := 1.000000;
begin
  for session_row in
    select *
    from public.storefront_intervention_sessions
    where reward_status = 'pending'
      and assigned_at <= timezone('utc', now()) - coalesce(p_cutoff, interval '4 hours')
    order by assigned_at asc
    for update skip locked
  loop
    update public.storefront_intervention_sessions
    set
      reward_status = 'failure',
      rewarded_at = timezone('utc', now()),
      metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
        'reward_source',
        'timeout_reconciliation'
      )
    where id = session_row.id
      and reward_status = 'pending';

    if found then
      update public.storefront_intervention_variants
      set
        beta = round(beta + 1, 6),
        failures_count = failures_count + 1,
        updated_at = timezone('utc', now())
      where id = session_row.variant_id;

      select
        coalesce(prior_alpha, 1.000000),
        coalesce(prior_beta, 1.000000)
      into
        variant_prior_alpha,
        variant_prior_beta
      from public.storefront_intervention_variants
      where id = session_row.variant_id;

      insert into public.storefront_trajectory_bandit_state (
        shop_domain,
        store_id,
        cohort_key,
        trajectory_key,
        variant_id,
        alpha,
        beta,
        successes_count,
        failures_count,
        first_seen_at,
        last_seen_at,
        created_at,
        updated_at
      )
      values (
        session_row.shop_domain,
        session_row.store_id,
        session_row.cohort_key,
        session_row.trajectory_key,
        session_row.variant_id,
        variant_prior_alpha,
        round(variant_prior_beta + 1, 6),
        0,
        1,
        session_row.assigned_at,
        timezone('utc', now()),
        timezone('utc', now()),
        timezone('utc', now())
      )
      on conflict (shop_domain, cohort_key, trajectory_key, variant_id)
      do update set
        beta = round(public.storefront_trajectory_bandit_state.beta + 1, 6),
        failures_count = public.storefront_trajectory_bandit_state.failures_count + 1,
        last_seen_at = timezone('utc', now()),
        updated_at = timezone('utc', now());

      processed := processed + 1;
    end if;
  end loop;

  return query select processed;
end;
$$;
