create table if not exists public.performance_metrics (
  id bigint generated by default as identity primary key,
  route_name text not null,
  route_runtime text not null default 'unknown',
  deployment_version text null,
  pilot_cohort text not null default 'pilot_default',
  rollout_key text not null default 'rule_based_pilot',
  shop_domain text not null,
  session_id text not null,
  requested_store_id text null,
  resolved_store_id text null,
  decision boolean not null default false,
  outcome_status text not null default 'success',
  response_status_code integer not null default 200,
  strategy text not null,
  intervention_type text not null default 'none',
  reason text not null,
  ingest_start_time timestamptz null,
  decision_end_time timestamptz not null default now(),
  total_duration_ms integer null,
  fetch_store_intervention_benchmarks_ms integer null,
  evaluate_ms integer null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists performance_metrics_route_name_created_at_idx
  on public.performance_metrics (route_name, created_at desc);

create index if not exists performance_metrics_shop_domain_created_at_idx
  on public.performance_metrics (shop_domain, created_at desc);
